alter table public."seniorPropertiesTYG"
  add column if not exists property_manager_canon text;

comment on column public."seniorPropertiesTYG".property_manager_canon
  is 'Canonicalized property manager name generated by the manager canonicalization pipeline; raw manager fields remain unchanged.';

create index if not exists senior_properties_tyg_property_manager_canon_idx
  on public."seniorPropertiesTYG" (property_manager_canon)
  where property_manager_canon is not null;;
