alter table public."student_propertiesTYG"
  add column if not exists property_manager_canon text;

comment on column public."student_propertiesTYG".property_manager_canon
  is 'Canonicalized property manager name generated by the manager canonicalization pipeline; raw Manager field remains unchanged.';

create index if not exists student_properties_tyg_property_manager_canon_idx
  on public."student_propertiesTYG" (property_manager_canon)
  where property_manager_canon is not null;;
